server:
  port: 9090
spring:
  datasource:
    #url: jdbc:mysql://1ocalhost:3306/demo?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis 数据库索引(默认为0)
    database: 0
    # Redis 服务器地址
    host: localhost
    # Redis 服务器连接端口
    port: 6379


# Logger Config
logging:
  level:
    top.lconcise: debug
