server:
  port: 9090

spring:
  application:
    name: Eureka-Server

eureka:
  instance:
    hostname: pro1
  client:
    service-url:
      defaultZone: http://user:123456@pro2:7070/eureka/
  server:
    enable-self-preservation: false
